name: Deploy - Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    steps:
      - uses: actions/checkout@v2

      - name: Build dotnet project
        working-directory: ./src
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish dotnet project
        working-directory: ./src
        run: dotnet publish --configuration Release --no-build --no-restore --output ./deploy

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: ./src/deploy/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_FOLDER }}
          dry-run: true
