name: Deploy - Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    steps:
      - uses: actions/checkout@v2

      - name: Build dotnet project
        working-directory: ./src
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish dotnet project
        working-directory: ./src
        run: dotnet publish --configuration Release --no-build --no-restore

      - name: Print environment variables
        run: |
          echo "FTP_SERVER: ${{ secrets.FTP_SERVER }}"
          echo "FTP_USERNAME: ${{ secrets.FTP_USERNAME }}"
          echo "FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}"
